import Head from "next/head";
import { CartTable } from "@/components/Shop/CartTable";
import { useAppDispatch, useAppSelector } from "@/hooks/redux";
import { useEffect, useState } from "react";
import { CartSummary } from "@/components/Shop/CartSummary";
import { Box } from "@mui/material";
import { useCreateOrderWoo } from "@/hooks/useCreateOrderWoo";
// import { useUpdateOrderWoo } from "@/hooks/useUpdateOrderWoo";
import { AddCoupon } from "@/components/Shop/AddCoupon";
import { Section } from "@/components/Layouts/Section";
import { Loader } from "@/components/Layouts/Loader";
import { transformDeleteOrderProducts } from "@/services/transformers/woocommerce/transformDeleteOrderProducts";
import { transformCreateOrderProducts } from "@/services/transformers/woocommerce/transformCreateOrderProducts";
import { useFetchUpdateOrderMutation } from "@/store/wooCommerce/wooCommerceApi";
import { setLineItemsIds } from "@/store/reducers/CurrentOrder";
import { transformLineItemsId } from "@/services/transformers/woocommerce/transformLineItemsId";
import styles from './styles.module.scss';
const Cart = () =>
{
    const { items, isLoading } = useAppSelector(state => state.Cart);
    const { currentOrder: { orderId, productLineIds } } = useAppSelector(state => state.currentOrder);
    const { createOrder, isLoading: isCreatingOrder, createdOrder } = useCreateOrderWoo();
    // const { updateOrder, isLoading: isUpdatingOrder, updatedOrder } = useUpdateOrderWoo();
    const [fetchUpdateOrder, { data: updatedOrder, isLoading: isUpdatingOrder }] = useFetchUpdateOrderMutation();
    const dispatch = useAppDispatch();
    const [products, setProducts] = useState(null);
    const [total, setTotal] = useState('0');
    const [isUpdating, setIsUpdating] = useState(false);

    const updateOrder = async () =>
    {
        if (items && items.length > 0)
        {
            if (!orderId)
            {
                createOrder(items);
            } else if (productLineIds && !isUpdatingOrder && !isUpdating)
            {
                setIsUpdating(true);
                const response = await fetchUpdateOrder({
                    credentials: {
                        line_items: [
                            ...transformDeleteOrderProducts(productLineIds),
                            ...transformCreateOrderProducts(items)
                        ]
                    },
                    id: orderId
                }).unwrap();
                console.log(productLineIds);
                console.log(response.line_items);
                dispatch(setLineItemsIds(transformLineItemsId(response.line_items)));
                // updateOrder(productLineIds, items, orderId);
                setIsUpdating(false);
            }
        }
    }

    useEffect(() =>
    {
        updateOrder();
    }, [items]);

    useEffect(() =>
    {
        if (createdOrder)
        {
            setTotal(createdOrder.total);
            setProducts(createdOrder.line_items);
        }
    }, [createdOrder]);

    useEffect(() =>
    {
        if (updatedOrder)
        {
            setTotal(updatedOrder.total);
            setProducts(updatedOrder.line_items);
        }
    }, [updatedOrder]);


    if (isCreatingOrder || isUpdatingOrder)
    {
        return <Loader size={100} thickness={4} />
    }

    return (
        <>
            <Head>
                <title>Shopping cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Section className="section" isContainer={true}>
                    <h1>Koszyk</h1>
                    <Box className={styles.Cart__content}>
                        <Box>
                            {updatedOrder && <CartTable products={updatedOrder.line_items} isLoading={isLoading} />}
                            <AddCoupon orderId={orderId && orderId} />
                        </Box>
                        <CartSummary total={total} sum={total} isLoading={isLoading} />
                    </Box>
                </Section>
            </main >
        </>
    );
}

export default Cart;