// import { useRouter } from "next/router";
import Head from "next/head";
// import variables from '../styles/variables.module.scss';
import { GetServerSidePropsContext } from "next";
import { customRestApi } from "@/services/CustomRestApi";
import { pageSchema } from "@/types/Services/customApi";
import { z } from "zod";
import { FC } from "react";
import { PageBuilder } from "@/components/PageBuilder";
import { AxiosResponse } from "axios";

const PagePropsSchema = z.object({
  page: pageSchema,
  error: z.string()
})

type PageProps = z.infer<typeof PagePropsSchema>;

const Page: FC<PageProps> = ({ page, error }) =>
{
  if (error || !page) throw new Error(error);

  if (page) console.log(page);
  // const router = useRouter();
  // const { slug } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <title>{page.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageBuilder sections={page.sections} />
      </main>
    </>
  );
}


// eslint-disable-next-line react-refresh/only-export-components
export async function getServerSideProps(context: GetServerSidePropsContext)
{
  const { params } = context;
  let slug = "homepage";

  if (params && Array.isArray(params.slug) && params.slug.length > 0)
    slug = params.slug[0];

  try
  {
    const { data } = await customRestApi.get(`pages/${slug}`) as AxiosResponse;

    if (data && data.data && data.data.item) return { props: { page: data.data.item } };
    else return { notFound: true };

  }
  catch (err)
  {
    return { props: { error: 'Server Error.' } }
  }
}

export default Page;
